ULOGA_KORISNIK = "korisnik"
ULOGA_PRODAVAC = "prodavac"
ULOGA_ADMIN = "admin"

PONEDELJAK = 0
UTORAK = 1
SREDA = 2
CETVRTAK = 3
PETAK = 4
SUBOTA = 5
NEDELJA = 6

STATUS_REALIZOVANA_KARTA = "realizovana_karta"
STATUS_NEREALIZOVANA_KARTA = "nerealizovana_karta"

